name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    volumes:
      - ./server/config.ini:/config.ini
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - ID=1
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-1.csv:/agency-1.csv
    networks:
      - testing_net
    depends_on:
      - server

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - ID=2
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-2.csv:/agency-2.csv
    networks:
      - testing_net
    depends_on:
      - server

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - ID=3
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-3.csv:/agency-3.csv
    networks:
      - testing_net
    depends_on:
      - server

  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - ID=4
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-4.csv:/agency-4.csv
    networks:
      - testing_net
    depends_on:
      - server

  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - ID=5
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-5.csv:/agency-5.csv
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
