SOCKET_MESSAGE_LENGTH_BYTES = 2

ENCODING_FORMAT = 'utf-8'
LINE_TERMINATOR = '\n'

BET_SEPARATOR = ';'
FIELD_SEPARATOR = ','
EXPECTED_BET_FIELDS = 6

BET_TYPE_MESSAGE = 'SEND_BETS'
WINNER_TYPE_MESSAGE = 'ASK_WINNER'

OK_RESPONSE = 'Ok'
ERROR_RESPONSE = 'Error'
REFUSED_RESPONSE = 'REFUSED'
