SOCKET_MESSAGE_LENGTH_BYTES = 2

ENCODING_FORMAT = 'utf-8'
LINE_TERMINATOR = '\n'

BET_SEPARATOR = ';'
FIELD_SEPARATOR = ','
EXPECTED_BET_FIELDS = 6

BET_TYPE_MESSAGE = 'SEND_BETS'
WINNER_TYPE_MESSAGE = 'ASK_WINNER'
END_CHUNKS_MESSAGE = 'END_CHUNKS'

OK_RESPONSE = 'OK'
ERROR_RESPONSE = 'ERROR'
REFUSED_RESPONSE = 'REFUSED'
ERROR_PROCESSING_CHUNKS_RESPONSE = 'ERROR_PROCESSING_CHUNKS'

MAX_MESSAGE_LENGTH = 8192